swagger: "2.0"
info:
  description: "Responsible for deciding whether an applicant is eligible for apply-for-healthy-start"
  title: "Eligibility Service"
  contact:
    name: "Department Of Health and Social Care"
    url: "https://github.com/DepartmentOfHealth-htbhf"
    email: "dh-htbhf-team@equalexperts.com"
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"
host: "N/A"
basePath: "/"
tags:
- name: "eligibility-controller"
  description: "Eligibility Controller"
- name: "eligibility-controller-v-2"
  description: "Eligibility Controller V 2"
paths:
  /v1/eligibility:
    post:
      tags:
      - "eligibility-controller"
      summary: "getDecision"
      operationId: "getDecisionUsingPOST"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "person"
        description: "person"
        required: true
        schema:
          $ref: "#/definitions/PersonDTO"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/EligibilityResponse"
        "201":
          description: "Created"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
      deprecated: false
  /v2/eligibility:
    post:
      tags:
      - "eligibility-controller-v-2"
      summary: "getIdentityAndEligibilityDecision"
      operationId: "getIdentityAndEligibilityDecisionUsingPOST"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "person"
        description: "person"
        required: true
        schema:
          $ref: "#/definitions/PersonDTOV2"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/CombinedIdentityAndEligibilityResponse"
        "201":
          description: "Created"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
      deprecated: false
definitions:
  AddressDTO:
    type: "object"
    required:
    - "addressLine1"
    - "postcode"
    - "townOrCity"
    properties:
      addressLine1:
        type: "string"
      addressLine2:
        type: "string"
      townOrCity:
        type: "string"
      postcode:
        type: "string"
        pattern: "([Gg][Ii][Rr] 0[Aa]{2})|((([A-Za-z][0-9]{1,2})|(([A-Za-z][A-Ha-hJ-Yj-y][0-9]{1,2})|(([A-Za-z][0-9][A-Za-z])|([A-Za-z][A-Ha-hJ-Yj-y][0-9][A-Za-z]?))))\\\
          s?[0-9][A-Za-z]{2})"
    title: "AddressDTO"
  ChildDTO:
    type: "object"
    properties:
      dateOfBirth:
        type: "string"
        format: "date"
        description: "The date of birth of the child"
    title: "ChildDTO"
    description: "A child in a household."
  CombinedIdentityAndEligibilityResponse:
    type: "object"
    properties:
      addressLine1Match:
        type: "string"
        enum:
        - "matched"
        - "not_matched"
        - "not_held"
        - "not_supplied"
        - "invalid_format"
        - "not_set"
      deathVerificationFlag:
        type: "string"
        enum:
        - "n/a"
        - "death_not_verified"
        - "limited_supporting_documentation"
        - "partial_supporting_documentation"
        - "full_supporting_documentation"
      dobOfChildrenUnder4:
        type: "array"
        items:
          $ref: "#/definitions/LocalDate"
      dwpHouseholdIdentifier:
        type: "string"
      eligibilityStatus:
        type: "string"
        enum:
        - "confirmed"
        - "not_confirmed"
        - "not_set"
      emailAddressMatch:
        type: "string"
        enum:
        - "matched"
        - "not_matched"
        - "not_held"
        - "not_supplied"
        - "invalid_format"
        - "not_set"
      hmrcHouseholdIdentifier:
        type: "string"
      identityStatus:
        type: "string"
        enum:
        - "matched"
        - "not_matched"
      mobilePhoneMatch:
        type: "string"
        enum:
        - "matched"
        - "not_matched"
        - "not_held"
        - "not_supplied"
        - "invalid_format"
        - "not_set"
      postcodeMatch:
        type: "string"
        enum:
        - "matched"
        - "not_matched"
        - "not_held"
        - "not_supplied"
        - "invalid_format"
        - "not_set"
      pregnantChildDOBMatch:
        type: "string"
        enum:
        - "matched"
        - "not_matched"
        - "not_held"
        - "not_supplied"
        - "invalid_format"
        - "not_set"
      qualifyingBenefits:
        type: "string"
        enum:
        - "universal_credit"
        - "employment_and_support_allowance"
        - "income_support"
        - "jobseekers_allowance"
        - "pension_credit"
        - "not_set"
    title: "CombinedIdentityAndEligibilityResponse"
  EligibilityResponse:
    type: "object"
    properties:
      children:
        type: "array"
        items:
          $ref: "#/definitions/ChildDTO"
      dwpHouseholdIdentifier:
        type: "string"
      eligibilityStatus:
        type: "string"
        enum:
        - "ELIGIBLE"
        - "INELIGIBLE"
        - "PENDING"
        - "NO_MATCH"
        - "ERROR"
        - "DUPLICATE"
      hmrcHouseholdIdentifier:
        type: "string"
      numberOfChildrenUnderFour:
        type: "integer"
        format: "int32"
        example: 1
        description: "The number of children under 4 that the person has (which will\
          \ include the number of children under 1)"
      numberOfChildrenUnderOne:
        type: "integer"
        format: "int32"
        example: 1
        description: "The number of children under 1 that the person has"
    title: "EligibilityResponse"
  PersonDTO:
    type: "object"
    required:
    - "address"
    - "dateOfBirth"
    - "firstName"
    - "lastName"
    - "nino"
    properties:
      firstName:
        type: "string"
      lastName:
        type: "string"
      nino:
        type: "string"
        pattern: "[a-zA-Z]{2}\\d{6}[a-dA-D]"
      dateOfBirth:
        type: "string"
        format: "date"
      address:
        $ref: "#/definitions/AddressDTO"
    title: "PersonDTO"
  PersonDTOV2:
    type: "object"
    required:
    - "addressLine1"
    - "dateOfBirth"
    - "nino"
    - "postcode"
    - "surname"
    properties:
      surname:
        type: "string"
      nino:
        type: "string"
        pattern: "^(?!BG|GB|NK|KN|TN|NT|ZZ)[A-CEGHJ-PR-TW-Z][A-CEGHJ-NPR-TW-Z](\\\
          d{6})[A-D]$"
      dateOfBirth:
        type: "string"
        format: "date"
      addressLine1:
        type: "string"
      postcode:
        type: "string"
        pattern: "^(GIR ?0AA|[A-PR-UWYZ]([0-9]{1,2}|([A-HK-Y][0-9]([0-9ABEHMNPRV-Y])?)|[0-9][A-HJKPS-UW])\
          \ ?[0-9][ABD-HJLNP-UW-Z]{2})$"
      emailAddress:
        type: "string"
        pattern: "(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$)"
      mobilePhoneNumber:
        type: "string"
        pattern: "^\\+44\\d{9,10}$"
      pregnantDependentDob:
        type: "string"
        format: "date"
    title: "PersonDTOV2"
