spring:
  jackson:
    default-property-inclusion: NON_NULL
  application:
    name: eligibility/api
    boot:
      admin:
        url: http://localhost:8100

server:
  port: 8100

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] [%X{session.id}][%X{request.id}] %-5level %logger{36} - %msg%n%rEx{full, org.springframework.web, org.springframework.boot, org.apache.catalina, org.apache.coyote, org.apache.tomcat, java.base}"
  level:
    ROOT: ${vcap.services.variable-service.credentials.eligibility-root-loglevel:info}
    uk.gov.dhsc: ${vcap.services.variable-service.credentials.eligibility-app-loglevel:debug}

eligibility-check-period-length: 28

dwp:
  base-uri: ${DWP_API_URI:http://localhost:8110}
  uc-monthly-income-threshold: 408.00

hmrc:
  base-uri: ${HMRC_API_URI:http://localhost:8130}
  ctc-annual-income-threshold: 16190.00

taskexecutor:
  threadpool:
    min-size: 2
    max-size: 200
